@host=http://localhost:3000

### 게시글 조회
GET {{host}}/api/post
Content-Type: application/json

### 게시글 상세 조회
GET {{host}}/api/post/1
Content-Type: application/json

### 게시글 작성
POST {{host}}/api/post
Content-Type: application/application/json
{
    "title": "안전하고 편안한 펫시팅",
    "content": "반려동물 훈련 노하우를 가진 준비된 펫시터!",
    "price": 50000,
    "startDate:,
    "endDate":,
    "career": "1년",
    "experience": "현재 고양이 집사입니다.",
}