@host=http://localhost:3000
@cookie=cookie-session-name=eyJwYXNzcG9ydCI6eyJ1c2VyIjoyfX0=;
@cookie-session-name.sig=ZE31dBIzzL0FojIrPG8pxbdRtiE;

### 리뷰 생성
POST {{host}}/api/store/3/reservation/2/review
Content-Type: application/json

{
    "comment": "펫시터님 덕분에 즐거운 여행이 되었어요!",
    "rating": 5
}

### 리뷰 조회
GET {{host}}/api/store/3/reviews

### 리뷰 수정
PUT {{host}}/api/store/3/reservation/2/review/3
Content-Type: application/json

{
    "comment": "펫시터님이 잘돌봐주셔서 너무 다행이에여ㅎㅎ",
    "rating": 4
}

### 리뷰 삭제
delete {{host}}/api/store/3/reservation/2/review/2
Content-Type: application/json